{
  programs.zsh = {
    enable = true;

    autosuggestion = {
      enable = true;
    };

    enableCompletion = true;

    initContent = ''
      eval "$(fnm env --use-on-cd)"

      export PATH="$HOME/.rd/bin:$PATH"
      export SOPS_AGE_KEY_FILE="$HOME/.config/sops/age/keys.txt"

      # Load secrets from the cached plain-text file
      if [ -f "$HOME/.config/nix-secrets/secrets.env" ]; then
        source "$HOME/.config/nix-secrets/secrets.env"
      fi

      # Alias to manually update the secrets cache (requires YubiKey)
      function update-secrets() {
        if [ -f "$HOME/.config/nix-secrets/secrets.yaml" ]; then
           echo "Decrypting secrets... (Touch YubiKey if needed)"
           _SECRETS=$(sops --decrypt --output-type json "$HOME/.config/nix-secrets/secrets.yaml")
           if [ $? -eq 0 ]; then
             echo "# Generated by update-secrets on $(date)" > "$HOME/.config/nix-secrets/secrets.env"
             echo "export NPM_TOKEN='$(echo "$_SECRETS" | jq -r '.npm_token // empty')'" >> "$HOME/.config/nix-secrets/secrets.env"
             echo "export GITLAB_ACCESS_TOKEN='$(echo "$_SECRETS" | jq -r '.gitlab_access_token // empty')'" >> "$HOME/.config/nix-secrets/secrets.env"
             echo "export NTFY_TOPIC_ID='$(echo "$_SECRETS" | jq -r '.ntfy_topic_id // empty')'" >> "$HOME/.config/nix-secrets/secrets.env"
             chmod 600 "$HOME/.config/nix-secrets/secrets.env"
             echo "Secrets updated and cached to ~/.config/nix-secrets/secrets.env"
             source "$HOME/.config/nix-secrets/secrets.env"
           else
             echo "Failed to decrypt secrets."
           fi
           unset _SECRETS
        else
           echo "No secrets.yaml found at ~/.config/nix-secrets/secrets.yaml"
        fi
      }

      # Wrapper to notify when a long-running Claude task finishes

    '';

    oh-my-zsh = {
      enable = true;
    };

    syntaxHighlighting = {
      enable = true;
    };
  };

  home.file.".hushlogin" = {
    text = "";
  };
}
