{
  config,
  lib,
  pkgs,
  ...
}:
let
  # Emacs 30's NS build covers both runtimes: it installs Emacs.app for GUI frames
  # (mac-app-util links it into ~/Applications) and the same binary runs
  # `emacs -nw` inside iTerm2/Alacritty. emacs30-macport renders text slightly
  # better on macOS but is a patched fork, so the standard build wins by default.
  # Linux gets the pgtk build wrapped in nixGL, like alacritty.
  emacsPackage =
    if pkgs.stdenv.hostPlatform.isDarwin then pkgs.emacs30 else config.lib.nixGL.wrap pkgs.emacs30-pgtk;
in
{
  imports = [
    ./colorscheme.nix
    ./keybinds.nix
    ./options.nix
    ./plugins
  ];

  # TRAMP writes temp files under the XDG cache, and a root-owned
  # ~/.cache/emacs (created once by something running under sudo) made every
  # remote file unreadable: "Creating file with prefix Permission denied", then
  # "File exists, but cannot be read" for anything opened over /docker:.
  # Creating it here as the user keeps that from recurring on a fresh machine.
  home.activation.emacsCacheDir = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    run mkdir -p "$HOME/.cache/emacs/tramp"
  '';

  programs.emacs = {
    enable = true;
    package = emacsPackage;
  };

  # A daemon under launchd (macOS) / systemd (Linux) is what makes "both runtimes"
  # one editor rather than two: `emacsclient -c` opens a GUI frame and
  # `emacsclient -nw` a terminal frame, against the same buffers and LSP servers.
  # $EDITOR deliberately stays on nvim (programs.nixvim.defaultEditor), so git and
  # the shell are untouched — this is an addition, not a replacement.
  services.emacs = {
    enable = true;
    client.enable = true;
    defaultEditor = false;
  };

  # early-init runs before the first frame is drawn, so killing package.el and
  # pre-painting the frame background here is what stops the white startup flash.
  # Its presence also makes Emacs adopt ~/.config/emacs as user-emacs-directory,
  # keeping backups/auto-saves/eln-cache out of $HOME — the same reason nvim puts
  # its undo/backup/swap dirs under $XDG_CONFIG_HOME. (If ~/.emacs.d/init.el ever
  # appears, Emacs prefers that directory and skips this file; the rest of the
  # config still loads, since it ships as default.el inside the Emacs package.)
  home.file.".config/emacs/early-init.el".text = ''
    ;;; early-init.el --- pre-frame setup -*- lexical-binding: t; -*-
    ;;; Generated by nix — edit modules/home-manager/features/development/emacs.

    ;; package-enable-at-startup is deliberately left ON. It is tempting to switch it
    ;; off since nix installs every package — but nix installs them *as an ELPA tree*,
    ;; and it is package.el's `package-activate-all' that walks it and loads each
    ;; package's autoloads. Disabling it leaves every command that is autoloaded
    ;; rather than explicitly required (git-link, forge-dispatch, the treemacs
    ;; sub-modes, diff-hl-margin-mode, ...) undefined at runtime.

    ;; Paint the frame in tokyonight storm before redisplay, so startup never
    ;; flashes the default white background.
    (push '(background-color . "#24283b") default-frame-alist)
    (push '(foreground-color . "#c0caf5") default-frame-alist)
    (push '(ns-transparent-titlebar . t) default-frame-alist)
    (push '(vertical-scroll-bars . nil) default-frame-alist)
    (push '(tool-bar-lines . 0) default-frame-alist)
    (setq frame-inhibit-implied-resize t
          inhibit-startup-screen t
          initial-scratch-message nil)

    ;; Native compilation is on in this build; keep its warnings out of the way and
    ;; its cache inside user-emacs-directory.
    (setq native-comp-async-report-warnings-errors 'silent
          native-comp-jit-compilation t)
    (when (fboundp 'startup-redirect-eln-cache)
      (startup-redirect-eln-cache
       (expand-file-name "eln-cache/" user-emacs-directory)))
  '';

  home.packages = [
    # consult-fd shells out to this; consult-ripgrep's ripgrep already arrives via
    # features/cli/ripgrep.nix.
    pkgs.fd

    # The terminal entry point. Unlike nvim, which reads $COLORTERM to decide it can
    # do 24-bit colour, Emacs 30 only believes the terminfo entry — so under the
    # TERM=xterm-256color that alacritty.nix sets, tokyonight would be quantised to
    # 256 colours. `em` declares xterm-direct instead, with nix's terminfo database
    # so the entry is guaranteed to exist (macOS ships an ncurses too old to have
    # it). GUI frames are `emacsclient -c`; both attach to the same daemon.
    (pkgs.writeShellScriptBin "em" ''
      exec env TERM=xterm-direct TERMINFO=${pkgs.ncurses}/share/terminfo \
        ${config.programs.emacs.finalPackage}/bin/emacsclient \
        -nw --alternate-editor="" "$@"
    '')
  ];
}
