# development emacs plugins vim

{
  lib,
  ...
}:
{
  programs.emacs.extraPackages =
    epkgs: with epkgs; [
      atomic-chrome
      evil
      evil-collection
      evil-numbers
      evil-surround
      exec-path-from-shell
      general
      helpful
      undo-fu-session
      vundo
      which-key
    ];

  # Ordered first (100). programs.emacs.extraConfig is a `lines`...

  # Ordered first (100). programs.emacs.extraConfig is a `lines` option, so every
  # per-concern file below appends to one generated default.el; mkOrder is what
  # fixes the order they land in. Everything after this block assumes evil,
  # evil-collection, general and which-key are already loaded, and the Colemak
  # rotation in keybinds.nix runs dead last (1500) so it can rewrite whatever
  # these plugins bound.

  programs.emacs.extraConfig = lib.mkOrder 100 ''
        ;;; -*- lexical-binding: t; -*-
        ;;; Generated by nix from modules/home-manager/features/development/emacs.
        ;;; Core: evil, evil-collection, general, which-key, sessions.

        ;; Startup runs with a high GC ceiling, then settles somewhere sane so long
        ;; sessions do not stutter. read-process-output-max matters for LSP: the
        ;; default 4k chokes on tsserver's replies.
        (setq gc-cons-threshold (* 512 1024 1024)
              read-process-output-max (* 4 1024 1024))
        (add-hook 'emacs-startup-hook
                  (lambda ()
                    (setq gc-cons-threshold (* 64 1024 1024)
                          gc-cons-percentage 0.2)))

        ;; This file is byte-compiled inside the nix build sandbox, where $HOME is a
        ;; read-only /homeless-shelter. The compiler evaluates every top-level `require',
        ;; and several packages (treemacs, obsidian, elgrep) write state under
        ;; `user-emacs-directory' as they load, which fails the build on "Read-only file
        ;; system". So point it somewhere writable when it is not.
        ;;
        ;; `eval-and-compile' is the load-bearing part: the byte-compiler only *evaluates*
        ;; require, defvar, defmacro and eval-{and,when}-compile forms. A plain `unless'
        ;; here would be compiled and then run at startup, long after the requires below
        ;; had already tried to write. This way it runs in both passes. At runtime
        ;; ~/.config/emacs exists and is writable, so it is a no-op.
        (eval-and-compile
          (unless (ignore-errors
                    (make-directory user-emacs-directory t)
                    (file-writable-p user-emacs-directory))
            (setq user-emacs-directory
                  (file-name-as-directory (make-temp-file "emacs-build-" t)))))

        ;; Keep `customize' writes out of the nix-generated config.
        (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
        (when (file-exists-p custom-file)
          (load custom-file :noerror :nomessage))

        ;; launchd hands the daemon a bare environment, so without this every LSP
        ;; server, prettierd and node would be missing from a GUI frame's PATH.
        (require 'exec-path-from-shell)
        (setq exec-path-from-shell-arguments '("-l")
              exec-path-from-shell-variables
              '("PATH" "MANPATH" "LANG" "LC_ALL" "SSH_AUTH_SOCK" "NIX_PATH"))
        (exec-path-from-shell-initialize)

        ;; evil-want-keybinding MUST be nil before evil loads, or evil-collection
        ;; refuses to take over the per-mode maps (magit, treemacs, dired, vterm,
        ;; ibuffer...). Those maps are precisely what the Colemak rotation rewrites
        ;; later, so this one line is what makes hnei reach the plugins.
        (setq evil-want-keybinding nil
              evil-want-integration t
              evil-want-C-u-scroll t
              evil-want-Y-yank-to-eol t
              evil-want-fine-undo t
              evil-undo-system 'undo-redo
              evil-search-module 'evil-search
              evil-ex-search-vim-style-regexp t
              evil-symbol-word-search t
              evil-respect-visual-line-mode t
              ;; splitbelow / splitright
              evil-split-window-below t
              evil-vsplit-window-right t)

        (require 'evil)
        (evil-mode 1)

        (require 'evil-collection)
        (evil-collection-init)

        ;; vim-surround
        (require 'evil-surround)
        (global-evil-surround-mode 1)

        ;; The + / - increment-decrement pair further down needs these commands.
        (require 'evil-numbers)

        (require 'general)
        (general-evil-setup)
        (general-override-mode 1)

        ;; leader = SPC, localleader = "," — globals.mapleader / maplocalleader. The
        ;; `override' keymap outranks every major and minor mode map, so SPC keeps
        ;; working inside magit, treemacs and dired instead of hitting their bindings.
        (general-create-definer my/leader
          :states '(normal visual motion)
          :keymaps 'override
          :prefix "SPC"
          :global-prefix "M-SPC")

        (general-create-definer my/localleader
          :states '(normal visual motion)
          :keymaps 'override
          :prefix ","
          :global-prefix "M-,")

        ;; which-key laid out like the nvim spec: "+" group prefix, 3 columns of
        ;; padding, 20..50 char descriptions, and a 500ms delay (timeoutlen). The nvim
        ;; groups all carry `icon = ""`, so plain "+name" labels match what you see.
        (require 'which-key)
        (setq which-key-idle-delay 0.5
              which-key-idle-secondary-delay 0.05
              which-key-prefix-prefix "+"
              which-key-separator " ➜ "
              ;; 0.25 of the frame paginated the leader menu once the config and
              ;; inbox sections took it to 24 entries -- half of them sat on a
              ;; second page behind C-h, which reads as bindings having vanished.
              which-key-side-window-max-height 0.45
              which-key-add-column-padding 3
              which-key-min-column-description-width 20
              which-key-max-description-length 50
              which-key-show-remaining-keys t
              which-key-sort-order 'which-key-key-order-alpha
              which-key-allow-evil-operators t)
        (which-key-mode 1)

        ;; auto-session's job: come back to where you were, with history, cursor
        ;; positions and a recent-file list (which is also what feeds SPC f r).
        (setq desktop-path (list user-emacs-directory)
              ;; Never ask about a stale lock file — a daemon that crashed leaves one
              ;; behind, and a prompt during startup would block every client frame.
              desktop-load-locked-desktop t
              desktop-restore-eager 10
              desktop-save t
              ;; Buffers, not windows: the daemon owns frame geometry, and restoring saved
              ;; frames on top of that fights emacsclient over which frame you land in.
              ;; The *split* is still worth keeping, and is handled separately below.
              desktop-restore-frames nil
              ;; Ten up front, the rest on an idle timer. Daemon startup already
              ;; runs to about fifteen seconds because every restored project
              ;; buffer triggers a synchronous direnv, and restoring everything
              ;; eagerly only lengthens that. The layout replay below forces the
              ;; remainder itself in the rare case a frame opens first.
              desktop-restore-eager 10
              recentf-max-saved-items 200
              history-length 500)
        (desktop-save-mode 1)
        (savehist-mode 1)
        (save-place-mode 1)
        (recentf-mode 1)

        ;; The window layout, saved apart from the desktop.
        ;;
        ;; desktop-save-mode brings the buffers back but not the panes, because
        ;; desktop-restore-frames recreates whole frames and a daemon cannot have
        ;; that -- it would build frames at login, before any client asked for one,
        ;; and then argue with emacsclient about which one you land in. A window
        ;; state is the half that is actually wanted: the splits and which buffer
        ;; sits in each, with no opinion about frames at all.
        (defvar my/window-state-file
          (expand-file-name "window-state.el" user-emacs-directory)
          "Where the last frame's pane layout is written.")

        (defvar my/window-state-restored nil
          "Non-nil once a layout has been replayed in this daemon's lifetime.")

        (defun my/save-window-state (&optional frame)
          "Write FRAME's pane layout for the next session.
    Hung on frame deletion rather than only on `kill-emacs-hook': the daemon
    usually outlives every frame, so by the time Emacs is actually exiting
    there is no layout left to record."
          (let ((frame (or frame (selected-frame))))
            (when (and (frame-live-p frame) (display-graphic-p frame))
              (condition-case nil
                  (let ((state (window-state-get (frame-root-window frame) t)))
                    (with-temp-file my/window-state-file
                      (prin1 state (current-buffer))))
                ;; A layout that cannot be written is not worth an error on the way
                ;; out the door.
                (error nil)))))

        (defun my/restore-window-state (&optional frame)
          "Replay the saved layout into FRAME.

    Once per daemon lifetime, and only into a frame that has nothing of its
    own to show: `emacsclient -c somefile' must land on that file, and the
    second frame of the day should not have the first frame's panes forced
    onto it.

    Runs at depth -90 so it precedes the dashboard's own new-frame hook,
    which calls `delete-other-windows' and would flatten the layout. After a
    successful replay the selected buffer is one of the restored ones, so
    that hook's *scratch*/*dashboard* guard declines on its own."
          (let ((frame (or frame (selected-frame))))
            (when (and (not my/window-state-restored)
                       (frame-live-p frame)
                       (display-graphic-p frame)
                       (member (buffer-name) '("*scratch*" "*dashboard*"))
                       (file-readable-p my/window-state-file))
              (setq my/window-state-restored t)
              ;; Any buffer still queued on the lazy-restore timer would be a
              ;; window that comes back empty, since the layout places buffers by
              ;; name. Normally the queue has drained long before a frame is asked
              ;; for; when it has not, finish it now rather than making every
              ;; daemon startup pay for the rare case.
              (when (bound-and-true-p desktop-buffer-args-list)
                (ignore-errors (desktop-lazy-complete)))
              (condition-case err
                  (let ((state (with-temp-buffer
                                 (insert-file-contents my/window-state-file)
                                 (read (current-buffer)))))
                    ;; 'safe: replay a layout saved on a larger display without
                    ;; failing on minimum window sizes. No `with-selected-frame'
                    ;; here -- that macro restores `current-buffer' when it exits,
                    ;; which silently undoes the selection below. window-state-put
                    ;; takes the target window as an argument and does not need
                    ;; the frame selected anyway.
                    (window-state-put state (frame-root-window frame) 'safe)
                    ;; window-state-put restores which window is selected but
                    ;; leaves `current-buffer' pointing at whatever it was --
                    ;; *scratch*, in a fresh frame. The dashboard's new-frame hook
                    ;; decides by `buffer-name', so without this it saw *scratch*,
                    ;; called `delete-other-windows' and flattened the layout that
                    ;; had just been replayed.
                    (let ((w (frame-selected-window frame)))
                      (when (window-live-p w) (select-window w t))))
                (error (message "Saved layout not restored: %S" err))))))

        (defun my/forget-window-state ()
          "Discard the saved layout, so the next frame opens on the dashboard."
          (interactive)
          (when (file-exists-p my/window-state-file)
            (delete-file my/window-state-file))
          (setq my/window-state-restored t)
          (message "Saved layout discarded."))

        (add-hook 'delete-frame-functions #'my/save-window-state)
        (add-hook 'kill-emacs-hook #'my/save-window-state)
        (add-hook 'server-after-make-frame-hook #'my/restore-window-state -90)

        ;; nvim's undofile: undo survives closing the buffer and restarting Emacs. The
        ;; directory is set before the `require' so the defcustom does not compute — and
        ;; create — its own default first.
        (setq undo-fu-session-directory (expand-file-name "undo/" user-emacs-directory))
        (require 'undo-fu-session)
        (undo-fu-session-global-mode 1)

        ;; firenvim's replacement — the GhostText extension in Chrome/Firefox hands the
        ;; focused textarea to this Emacs, so GitHub/GitLab comment boxes get evil.
        (require 'atomic-chrome)
        (setq atomic-chrome-buffer-open-style 'frame
              atomic-chrome-default-major-mode 'gfm-mode
              atomic-chrome-url-major-mode-alist
              '(("github\\.com" . gfm-mode)
                ("gitlab\\.com" . gfm-mode)))
        (atomic-chrome-start-server)
  '';
}
