{
  lib,
  ...
}:
{
  programs.emacs.extraPackages =
    epkgs: with epkgs; [
      atomic-chrome
      evil
      evil-collection
      evil-numbers
      evil-surround
      exec-path-from-shell
      general
      helpful
      undo-fu-session
      vundo
      which-key
    ];

  # Ordered first (100). programs.emacs.extraConfig is a `lines` option, so every
  # per-concern file below appends to one generated default.el; mkOrder is what
  # fixes the order they land in. Everything after this block assumes evil,
  # evil-collection, general and which-key are already loaded, and the Colemak
  # rotation in keybinds.nix runs dead last (1500) so it can rewrite whatever
  # these plugins bound.
  programs.emacs.extraConfig = lib.mkOrder 100 ''
    ;;; -*- lexical-binding: t; -*-
    ;;; Generated by nix from modules/home-manager/features/development/emacs.
    ;;; Core: evil, evil-collection, general, which-key, sessions.

    ;; Startup runs with a high GC ceiling, then settles somewhere sane so long
    ;; sessions do not stutter. read-process-output-max matters for LSP: the
    ;; default 4k chokes on tsserver's replies.
    (setq gc-cons-threshold (* 512 1024 1024)
          read-process-output-max (* 4 1024 1024))
    (add-hook 'emacs-startup-hook
              (lambda ()
                (setq gc-cons-threshold (* 64 1024 1024)
                      gc-cons-percentage 0.2)))

    ;; This file is byte-compiled inside the nix build sandbox, where $HOME is a
    ;; read-only /homeless-shelter. The compiler evaluates every top-level `require',
    ;; and several packages (treemacs, obsidian, elgrep) write state under
    ;; `user-emacs-directory' as they load, which fails the build on "Read-only file
    ;; system". So point it somewhere writable when it is not.
    ;;
    ;; `eval-and-compile' is the load-bearing part: the byte-compiler only *evaluates*
    ;; require, defvar, defmacro and eval-{and,when}-compile forms. A plain `unless'
    ;; here would be compiled and then run at startup, long after the requires below
    ;; had already tried to write. This way it runs in both passes. At runtime
    ;; ~/.config/emacs exists and is writable, so it is a no-op.
    (eval-and-compile
      (unless (ignore-errors
                (make-directory user-emacs-directory t)
                (file-writable-p user-emacs-directory))
        (setq user-emacs-directory
              (file-name-as-directory (make-temp-file "emacs-build-" t)))))

    ;; Keep `customize' writes out of the nix-generated config.
    (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
    (when (file-exists-p custom-file)
      (load custom-file :noerror :nomessage))

    ;; launchd hands the daemon a bare environment, so without this every LSP
    ;; server, prettierd and node would be missing from a GUI frame's PATH.
    (require 'exec-path-from-shell)
    (setq exec-path-from-shell-arguments '("-l")
          exec-path-from-shell-variables
          '("PATH" "MANPATH" "LANG" "LC_ALL" "SSH_AUTH_SOCK" "NIX_PATH"))
    (exec-path-from-shell-initialize)

    ;; evil-want-keybinding MUST be nil before evil loads, or evil-collection
    ;; refuses to take over the per-mode maps (magit, treemacs, dired, vterm,
    ;; ibuffer...). Those maps are precisely what the Colemak rotation rewrites
    ;; later, so this one line is what makes hnei reach the plugins.
    (setq evil-want-keybinding nil
          evil-want-integration t
          evil-want-C-u-scroll t
          evil-want-Y-yank-to-eol t
          evil-want-fine-undo t
          evil-undo-system 'undo-redo
          evil-search-module 'evil-search
          evil-ex-search-vim-style-regexp t
          evil-symbol-word-search t
          evil-respect-visual-line-mode t
          ;; splitbelow / splitright
          evil-split-window-below t
          evil-vsplit-window-right t)

    (require 'evil)
    (evil-mode 1)

    (require 'evil-collection)
    (evil-collection-init)

    ;; vim-surround
    (require 'evil-surround)
    (global-evil-surround-mode 1)

    ;; The + / - increment-decrement pair further down needs these commands.
    (require 'evil-numbers)

    (require 'general)
    (general-evil-setup)
    (general-override-mode 1)

    ;; leader = SPC, localleader = "," — globals.mapleader / maplocalleader. The
    ;; `override' keymap outranks every major and minor mode map, so SPC keeps
    ;; working inside magit, treemacs and dired instead of hitting their bindings.
    (general-create-definer my/leader
      :states '(normal visual motion)
      :keymaps 'override
      :prefix "SPC"
      :global-prefix "M-SPC")

    (general-create-definer my/localleader
      :states '(normal visual motion)
      :keymaps 'override
      :prefix ","
      :global-prefix "M-,")

    ;; which-key laid out like the nvim spec: "+" group prefix, 3 columns of
    ;; padding, 20..50 char descriptions, and a 500ms delay (timeoutlen). The nvim
    ;; groups all carry `icon = ""`, so plain "+name" labels match what you see.
    (require 'which-key)
    (setq which-key-idle-delay 0.5
          which-key-idle-secondary-delay 0.05
          which-key-prefix-prefix "+"
          which-key-separator " ➜ "
          which-key-add-column-padding 3
          which-key-min-column-description-width 20
          which-key-max-description-length 50
          which-key-show-remaining-keys t
          which-key-sort-order 'which-key-key-order-alpha
          which-key-allow-evil-operators t)
    (which-key-mode 1)

    ;; auto-session's job: come back to where you were, with history, cursor
    ;; positions and a recent-file list (which is also what feeds SPC f r).
    (setq desktop-path (list user-emacs-directory)
          ;; Never ask about a stale lock file — a daemon that crashed leaves one
          ;; behind, and a prompt during startup would block every client frame.
          desktop-load-locked-desktop t
          desktop-restore-eager 10
          desktop-save t
          ;; Buffers, not windows: the daemon owns frame geometry, and restoring saved
          ;; frames on top of that fights emacsclient over which frame you land in.
          desktop-restore-frames nil
          recentf-max-saved-items 200
          history-length 500)
    (desktop-save-mode 1)
    (savehist-mode 1)
    (save-place-mode 1)
    (recentf-mode 1)

    ;; nvim's undofile: undo survives closing the buffer and restarting Emacs. The
    ;; directory is set before the `require' so the defcustom does not compute — and
    ;; create — its own default first.
    (setq undo-fu-session-directory (expand-file-name "undo/" user-emacs-directory))
    (require 'undo-fu-session)
    (undo-fu-session-global-mode 1)

    ;; firenvim's replacement — the GhostText extension in Chrome/Firefox hands the
    ;; focused textarea to this Emacs, so GitHub/GitLab comment boxes get evil.
    (require 'atomic-chrome)
    (setq atomic-chrome-buffer-open-style 'frame
          atomic-chrome-default-major-mode 'gfm-mode
          atomic-chrome-url-major-mode-alist
          '(("github\\.com" . gfm-mode)
            ("gitlab\\.com" . gfm-mode)))
    (atomic-chrome-start-server)
  '';
}
