{
  pkgs,
  config,
  lib,
  ...
}:
let
  # ─── Identities ───────────────────────────────────────────────────────────
  # Client-specific identities are loaded from ~/.config/nix-secrets/git-identities.nix
  # if present (kept out of the public nix-config repo). When the file is
  # missing, we fall back to a minimal personal-only configuration so a fresh
  # machine still builds.
  #
  # Schema for the private file is documented inside it; the short version:
  #   { personal = { name; email; signingKey?; };
  #     <client> = { name; email; signingKey?; }; … }
  identitiesPath = "${config.home.homeDirectory}/.config/nix-secrets/git-identities.nix";

  fallbackIdentities = {
    personal = {
      name = "Anonymous";
      email = "anonymous@example.com";
    };
  };

  identities =
    if builtins.pathExists identitiesPath then import identitiesPath else fallbackIdentities;

  # Personal is the default user; every other key in `identities` is a client
  # whose work lives under ~/Development/<name>/.
  defaultIdentity =
    identities.personal or {
      name = "Anonymous";
      email = "anonymous@example.com";
    };
  clientIdentities = builtins.removeAttrs identities [ "personal" ];

  # identity → [user] block (omits signingKey if absent so empty placeholders
  # don't break `commit.gpgsign = true` once enabled).
  userBlock =
    id:
    {
      name = id.name;
      email = id.email;
    }
    // (if id ? signingKey then { signingKey = id.signingKey; } else { });

  # ─── Generated allowed_signers content ────────────────────────────────────
  # One line per identity. Identities without a signingKey land as commented
  # placeholders so the file remains valid SSH-allowed-signers format.
  signerLine =
    name: id:
    if id ? signingKey then
      "${id.email} ${id.signingKey}\n"
    else
      "# ${id.email}  ssh-ed25519 AAAA…paste-${name}-public-key\n";

  allowedSignersText =
    ''
      # Generated by nix-config from ${identitiesPath}
      # Do not hand-edit — rebuild after updating the identities file instead.
    ''
    + builtins.concatStringsSep "" (lib.mapAttrsToList signerLine identities);
in
{
  programs.git = {
    enable = true;
    package = pkgs.gitFull;

    settings = {
      # Default identity. Applies in directories that don't match any include.
      user = userBlock defaultIdentity;

      alias = {
        co = "checkout";
        st = "status";
        br = "branch";
        last = "log -1 HEAD";
        unstage = "reset HEAD --";
        dc = "diff --cached";
      };

      pull = {
        rebase = false;
      };

      init.defaultBranch = "main";
      push.autoSetupRemote = true;
      fetch.prune = true;

      # SSH signing infrastructure. Per-identity signingKey comes from the
      # private identities file. commit.gpgsign stays off until every loaded
      # identity has a signingKey — flip it on at the call site once you've
      # populated all six.
      gpg = {
        format = "ssh";
        ssh = {
          allowedSignersFile = "${config.home.homeDirectory}/.config/git/allowed_signers";
        };
      };

      # commit.gpgsign = true;
      # tag.gpgsign = true;
    }
    // (
      if pkgs.stdenv.hostPlatform.isLinux then
        {
          credential = {
            credentialStore = "secretservice";
            helper = [
              "manager"
              "cache --timeout 21600"
            ];
          };
        }
      else
        {
          credential = {
            helper = "osxkeychain";
          };
        }
    );

    # One gitdir-conditional include per client identity, generated from the
    # private file. The convention is: client `acme` → `~/Development/acme/`.
    # Reorganize your repos into matching subdirectories OR add per-repo
    # entries in ~/.config/nix-secrets/git-identities.nix as needed.
    includes = lib.mapAttrsToList (name: id: {
      condition = "gitdir:~/Development/${name}/";
      contents.user = userBlock id;
    }) clientIdentities;
  };

  # allowed_signers — declaratively written from the private identities file.
  home.file.".config/git/allowed_signers".text = allowedSignersText;
}
