# development emacs plugins social

{
  config,
  lib,
  pkgs,
  ...
}:
{
  programs.emacs.extraPackages =
    epkgs: with epkgs; [
      telega
      slack
    ];

  # telega renders the login QR code by shelling out to qrencode....

  # telega renders the login QR code by shelling out to qrencode. Without it on
  # PATH the QR branch is skipped silently and telega falls back to asking for a
  # phone number -- see the login note in extraConfig below.

  # discordo is the Discord client: a terminal program, which `my/discord' below
  # runs inside vterm. It is on PATH as well so it works from a plain shell too;
  # the Emacs side calls it by store path, so the daemon's PATH does not matter.

  home.packages = [
    pkgs.qrencode
    pkgs.discordo
  ];

  # discordo's keys, for Colemak and for life inside vterm

  # discordo reads config.toml from the OS config directory -- Application Support
  # on macOS, ~/.config elsewhere -- and decodes it over its built-in defaults, so
  # the file only needs the keys that change. It only ever reads it, so a
  # read-only store link is fine here, unlike OmniWM's settings.

  # Two kinds of change. The first four are keys discordo can never receive
  # inside vterm: C-g is keyboard-quit, C-h is help, a terminal has no way to send
  # C-. at all, and C-\ is the way back to evil's normal state (keybinds.nix). The
  # rest is the Colemak rotation every other tool here gets: n and e move down and
  # up, and the letters they displace take over what n, e and i did -- edit moves
  # from e to k, copy-ID from i to l. Nothing else in discordo binds n or e.

  home.file."${
    if pkgs.stdenv.hostPlatform.isDarwin then "Library/Application Support" else ".config"
  }/discordo/config.toml".text =
  ''
    # Generated by nix -- plugins/social in nix-config. Only what differs
    # from discordo's defaults; everything else is theirs.

    [keybinds]
    focus_guilds_tree = "ctrl+s"
    focus_previous = "ctrl+o"
    toggle_help = "ctrl+q"

    [keybinds.composer]
    open_file_picker = "ctrl+f"
  ''
  + lib.optionalString (config.features.productivity.keyboard.layout == "colemak") ''

    [keybinds.guilds_tree]
    select_up = "e"
    select_down = "n"
    yank_id = "l"

    [keybinds.messages_list]
    select_up = "e"
    select_down = "n"
    scroll_up = "E"
    scroll_down = "N"
    edit = "k"
    yank_id = "l"
  '';

  # No notifier binary. The banner is posted by Emacs itself...

  # No notifier binary. The banner is posted by Emacs itself.

  # terminal-notifier used to be installed here, and it is not needed now: a
  # notification is attributed to the bundle of the process that posts it, and
  # the daemon already runs from inside Emacs.app. Posting from within Emacs --
  # which is what =my/notify= in plugins/ui/notifications.nix does -- therefore
  # gets Emacs' own icon without a helper, and without terminal-notifier's habit
  # of stealing focus for the instant it is frontmost.

  programs.emacs.extraConfig = ''
    ;;; Telegram — telega.el, a real client rather than a bridge.
    ;;;
    ;;; It talks to Telegram through tdlib, the same library the official desktop
    ;;; client uses, so chats, media and replies all work. The session is kept
    ;;; under ~/.telega and survives restarts.
    ;;;
    ;;; First run should show a QR CODE to scan from a phone that is already
    ;;; logged in, not ask for a phone number. telega only falls back to the
    ;;; phone prompt when the QR branch is unavailable:
    ;;;
    ;;;   (if (and (not telega--relogin-with-phone-number)
    ;;;            telega-use-images
    ;;;            (or (executable-find "qrencode") telega-use-docker))
    ;;;       (telega--requestQrCodeAuthentication)
    ;;;     (telega--setAuthenticationPhoneNumber (read-string ...)))
    ;;;
    ;;; and that fallback is a dead end on an account whose login codes are
    ;;; delivered in-app: Telegram reports next_type = null, so it never offers
    ;;; SMS, and the code lands in a service chat that may not be visible.
    ;;; qrencode is now installed above, and telega-use-images is set below when
    ;;; telega loads rather than when this file does.
    ;;;
    ;;; Chrome, the Google suite and the rest of the app list stay outside the editor
    ;;; on purpose — nothing in Emacs improves on them, and pretending otherwise
    ;;; would mean a worse Gmail, not a better Emacs. GhostText (see
    ;;; plugins/vim/default.nix) is the useful half of the browser integration: it
    ;;; hands any textarea to Emacs with evil and the full config attached.

    ;; Autoloaded, not required: telega is something you open on purpose, and loading
    ;; a whole chat client (and its tdlib session handling) into every Emacs startup
    ;; buys nothing. `M-x telega' or SPC o t pulls it in.
    (autoload 'telega "telega" nil t)

    ;; Your own Telegram API credentials, or no login code ever arrives.
    ;;
    ;; telega ships
    ;;
    ;;   (defconst telega-app '(72239 . "bbf972f94cc6f0ee5da969d8d42a6c76"))
    ;;
    ;; -- one api_id shared by every telega user and published in the package
    ;; source. Telegram silently stops delivering login codes for api_ids it
    ;; considers abused, and the failure gives nothing away: the auth state
    ;; reaches authorizationStateWaitCode with
    ;; authenticationCodeTypeTelegramMessage, no message is delivered to any
    ;; session or by SMS, and anything entered comes back PHONE_CODE_INVALID.
    ;;
    ;; Register an application at https://my.telegram.org/apps and put the pair
    ;; in ~/.config/telega/app.el, which is deliberately outside this public
    ;; repository because api_hash is a credential:
    ;;
    ;;   ;;; app.el --- credentials  -*- lexical-binding: t; -*-
    ;;   (setq telega-app '(1234567 . "0123456789abcdef0123456789abcdef"))
    ;;
    ;; The cookie on the first line matters: Emacs 31 warns about every file it
    ;; loads without one, and this file is loaded on every start.
    ;;
    ;; after-load, not here: telega-app is a defconst, so loading telega.el
    ;; would overwrite anything set beforehand. Missing file is not an error --
    ;; telega still loads, and still cannot log in.
    (with-eval-after-load 'telega
      (let ((f (expand-file-name "~/.config/telega/app.el")))
        (when (file-readable-p f)
          (load f nil :nomessage))))

    ;; Asked when telega loads, not when this file does.
    ;;
    ;; This was `telega-use-images (display-graphic-p)' in the setq below, and
    ;; under `emacs --fg-daemon' that runs with no graphical frame in
    ;; existence, so it was pinned nil for the life of the daemon. Images off
    ;; also disables telega's QR login branch, which is why first run asked for
    ;; a phone number instead of showing a code to scan.
    ;;
    ;; telega is autoloaded and opened deliberately, so load time is the frame
    ;; you invoked it from -- the right one to ask.
    (with-eval-after-load 'telega
      (setq telega-use-images (display-graphic-p)))

    ;; Keeps telega's unread counters current, which is what the my/telega
    ;; segment in statusline.nix reads. Its own mode-line string goes to
    ;; `mode-line-misc-info', which this modeline does not render; the mode is
    ;; enabled for the bookkeeping, not the string.
    ;;
    ;; It does not carry the repaint with it. `telega-mode-line-update' calls
    ;; `force-mode-line-update' with no argument, from a buffer no window is
    ;; showing, so nothing is marked for redisplay and the tab-bar badge stays
    ;; on its old number. statusline.nix advises the two update handlers to
    ;; repaint every frame; see my/status-repaint there.
    (with-eval-after-load 'telega
      (telega-mode-line-mode 1))

    ;; Desktop notifications on macOS.
    ;;
    ;; telega-notifications--notify calls `notifications-notify', which is
    ;; D-Bus and therefore Linux-only: on darwin telega-notifications-mode runs
    ;; and silently produces nothing. This is the bridge.
    ;;
    ;; Everything about HOW a banner is posted lives in `my/notify' and the
    ;; alert style behind it, in plugins/ui/notifications.nix -- posted from
    ;; inside Emacs' own bundle so the banner carries Emacs' icon and raises
    ;; Emacs when clicked, deferred to an idle moment so the AppleScript call
    ;; never blocks a keystroke, and coalesced per title, which here means per
    ;; chat. None of that is telega's business, and every other notification in
    ;; this config wants the same three things.
    ;;
    ;; What is telega's business is the shape of NOTIFY-SPEC, which is all that
    ;; is left here. Text properties are stripped on the way through: telega's
    ;; :title and :body carry faces and image specs meant for the Emacs display.
    ;;
    ;; Not terminal-notifier, which this used to be. It is a GUI app bundle:
    ;; posting a banner makes it frontmost for an instant, and macOS then hands
    ;; focus back to whatever was frontmost before Emacs -- so a message
    ;; arriving while you type threw you into the app you were in previously.
    ;; -sender does not prevent it.
    ${lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
      (defun my/telega-notify-macos (notify-spec)
        "Show NOTIFY-SPEC as a desktop notification, in place of D-Bus."
        (my/notify (or (plist-get notify-spec :title) "Telegram")
                   (or (plist-get notify-spec :body) "")))

      (with-eval-after-load 'telega
        (advice-add 'telega-notifications--notify
                    :override #'my/telega-notify-macos)
        (telega-notifications-mode 1))
    ''}

    (setq telega-directory (expand-file-name "~/.telega")
          telega-emoji-use-images nil
          telega-chat-fill-column 80
          telega-completing-read-function #'completing-read)

    ;; Connected from the first frame, rather than when you remember to open it.
    ;;
    ;; The autoload above stays exactly as it is: nothing here loads telega at
    ;; init, it starts it once a frame exists. `telega' with a non-nil argument
    ;; is telega's own "start without popping the root buffer", so the client
    ;; connects, the notifications fire and the unread count in the modeline is
    ;; a real number -- all of which need a running telega-server, and none of
    ;; which happened on a day the root buffer was never opened.
    ;;
    ;; A graphical frame is required, and that is not fussiness. As the note
    ;; above says, `telega-use-images' is read when telega loads, so loading it
    ;; from a terminal frame pins images off for the life of the daemon. If the
    ;; first frame of the session is a tty, the start is left armed for the
    ;; next graphical one instead.
    ;;
    ;; And only when there is a session on disk to resume. td.binlog is where
    ;; tdlib keeps the authorisation; without it `telega' does not connect, it
    ;; starts the login flow -- a QR code, unasked for, in a frame you opened
    ;; to do something else.
    (defun my/telega--session-p ()
      "Non-nil when tdlib has a session on disk to resume."
      (file-exists-p (expand-file-name "td.binlog" telega-directory)))

    (defun my/telega-start-in-background ()
      "Connect telega without showing it."
      (when (my/telega--session-p)
        (if (display-graphic-p)
            (unless (and (fboundp 'telega-server-live-p) (telega-server-live-p))
              (telega t))
          (add-hook 'server-after-make-frame-hook #'my/telega--start-when-graphic))))

    (defun my/telega--start-when-graphic ()
      "Start telega if this frame is graphical, then stand down."
      (when (display-graphic-p)
        (remove-hook 'server-after-make-frame-hook #'my/telega--start-when-graphic)
        (my/telega-start-in-background)))

    (add-hook 'my/startup-hook #'my/telega-start-in-background)

    (custom-set-faces
     `(telega-msg-heading ((t (:foreground ,(my/tn 'blue) :weight bold))))
     `(telega-unmuted-count ((t (:foreground ,(my/tn 'green))))))

    ;; Keys telega does not give you, and one it gives you that evil eats.
    ;;
    ;; RET in a chat buffer is `telega-chatbuf-newline-or-input-send', which
    ;; decides between the two by looking at the input. Under evil's insert
    ;; state that decision does not survive: RET drops back to normal state and
    ;; sends nothing. Binding it per-state removes the guesswork -- RET sends
    ;; from either state, S-RET is the newline -- which is also the behaviour
    ;; every other chat client has.
    ;;
    ;; Folders have no key of their own upstream: `telega-filter-by-folder' is
    ;; only reachable as "/ f". F opens the folder *view* (all folders as
    ;; sections) and U filters to unread, which together are the "jump to work,
    ;; jump to unread" that "/ f" makes into a two-step. Both keys are free in
    ;; `telega-root-mode-map'.
    ;;
    ;; Bound twice for the root map on purpose: evil-collection may leave that
    ;; buffer in emacs state, where the plain map binding is what runs, or in
    ;; normal state, where only the evil one is consulted.
    ;; Getting out of a chat.
    ;;
    ;; telega-chat-mode-map binds four keys -- TAB, S-TAB, RET and C-l -- and
    ;; none of them leaves the buffer, so there is genuinely no way back to the
    ;; chat list short of the generic buffer commands. q is the key every other
    ;; Emacs list/detail pair uses, and in evil normal state it would otherwise
    ;; start recording a macro, which is not something wanted mid-conversation.
    (defun my/telega-back ()
      "Return to the telega root buffer from a chat."
      (interactive)
      (let ((root (get-buffer telega-root-buffer-name)))
        (if (buffer-live-p root)
            (progn (bury-buffer) (switch-to-buffer root))
          (bury-buffer))))

    (with-eval-after-load 'telega
      (require 'evil nil t)
      (define-key telega-chat-mode-map (kbd "C-c C-q") #'my/telega-back)
      (define-key telega-root-mode-map (kbd "F") #'telega-view-folders)
      (define-key telega-root-mode-map (kbd "U") #'telega-filter-by-unread)
      (when (fboundp 'evil-define-key*)
        (evil-define-key* 'normal telega-root-mode-map
          (kbd "F") #'telega-view-folders
          (kbd "U") #'telega-filter-by-unread)
        (evil-define-key* 'insert telega-chat-mode-map
          (kbd "RET") #'telega-chatbuf-input-send
          (kbd "S-<return>") #'newline)
        (evil-define-key* 'normal telega-chat-mode-map
          (kbd "RET") #'telega-chatbuf-input-send
          ;; gr, next to evil's other g-prefixed verbs. Opens telega's reaction
          ;; picker on the message at point.
          (kbd "gr") #'telega-msg-add-reaction
          (kbd "q") #'my/telega-back)
        ;; V undoes F. telega-view-reset returns the root buffer to the plain
        ;; chat list from the folder view -- without it F is a one-way door.
        (evil-define-key* 'normal telega-root-mode-map
          (kbd "V") #'telega-view-reset))
      (define-key telega-root-mode-map (kbd "V") #'telega-view-reset))

    ;;; Slack — emacs-slack, the maintained fork (github.com/emacs-slack/emacs-slack).
    ;;;
    ;;; A real client over Slack's own web API and websocket, in lui buffers
    ;;; like circe's. Workspaces you do not administer -- OWASP's, and most
    ;;; community ones -- will not let you install an app for a proper token,
    ;;; so this logs in with the browser session's pair instead: an xoxc-
    ;;; token and the d cookie. `M-x describe-variable RET
    ;;; slack-refresh-token-instructions' has the steps for finding both.
    ;;;
    ;;; Together they are a live login, as good as your password to that
    ;;; workspace, so they stay out of this public repository. Each workspace
    ;;; in `my/slack-teams' reads two lines from ~/.authinfo.gpg:
    ;;;
    ;;;   machine owasp.slack.com login token  password xoxc-...
    ;;;   machine owasp.slack.com login cookie password "xoxd-...; d-s=...; lc=..."
    ;;;
    ;;; Quoted because the cookie has spaces in it. Signing out of Slack in
    ;;; that browser ends the session and the pair with it; fetch it again.
    ;;;
    ;;; Notifications need nothing here: emacs-slack posts through `alert',
    ;;; and alert's default style is my/macos (plugins/ui/notifications.nix).
    ;;; Only DMs, private channels, mentions and followed threads notify, which
    ;;; on a workspace the size of OWASP's is the right amount.
    ;;;
    ;;; Not started in the background the way telega is. The credentials live
    ;;; in ~/.authinfo.gpg, and reading that at startup would ask for the GPG
    ;;; passphrase on every Emacs launch. Notifications therefore start once
    ;;; SPC o l has connected, not before.
    (defvar my/slack-teams '("owasp")
      "Slack workspaces to connect, by subdomain: NAME.slack.com.")

    (defun my/slack--secret (host user)
      "The auth-source password for USER at HOST, or nil."
      (auth-source-pick-first-password :host host :user user))

    (defun my/slack--register-teams ()
      "Register every workspace in `my/slack-teams' that has credentials.
    Returns how many were registered."
      (let ((count 0))
        (dolist (name my/slack-teams count)
          (let* ((host (format "%s.slack.com" name))
                 (token (my/slack--secret host "token")))
            (when token
              (slack-register-team :name name
                                   :token token
                                   :cookie (my/slack--secret host "cookie")
                                   :default (zerop count)
                                   :full-and-display-names t
                                   ;; Not for a modeline: nothing here draws
                                   ;; emacs-slack's own string. It is what lets
                                   ;; a counts refresh reach
                                   ;; `slack-update-modeline', which is where
                                   ;; the tab-bar badge in statusline.nix
                                   ;; takes its number.
                                   :modeline-enabled t)
              (setq count (1+ count)))))))

    ;; One key for both halves. The first press registers and connects; once
    ;; connected, it picks a room -- unread ones first, all of them when
    ;; nothing is unread, because `slack-select-unread-rooms' errors instead
    ;; of offering the rest.
    (defun my/slack ()
      "Connect to Slack the first time; after that, pick a room to read."
      (interactive)
      (require 'slack)
      (when (and (hash-table-empty-p slack-teams-by-token)
                 (zerop (my/slack--register-teams)))
        (user-error "No Slack credentials in ~/.authinfo.gpg -- see plugins/social"))
      (if (null (slack-team-connected-list))
          (progn
            (slack-start)
            (message "Slack: connecting -- SPC o l again to pick a room"))
        (condition-case nil
            (slack-select-unread-rooms)
          (error (slack-select-rooms)))))

    ;; One workspace today, so never ask which one.
    (setq slack-prefer-current-team t)

    ;; q leaves a Slack buffer, as it leaves every other list/detail pair in
    ;; this config, instead of starting a macro; gr reacts, as it does in
    ;; telega. Every message buffer derives from slack-mode, and the file,
    ;; search and thread lists from slack-buffer-mode.
    (with-eval-after-load 'slack
      (when (fboundp 'evil-define-key*)
        (evil-define-key* 'normal slack-mode-map
          (kbd "q") #'quit-window
          (kbd "gr") #'slack-message-add-reaction)
        (evil-define-key* 'normal slack-buffer-mode-map
          (kbd "q") #'quit-window)))

    ;;; Discord — discordo, a terminal client, in its own vterm buffer.
    ;;;
    ;;; Nothing Emacs-native is worth running. bitlbee-discord, the usual
    ;;; bridge into ERC, has not had a release since 2020, and a Matrix bridge
    ;;; means running a homeserver for one chat app. discordo is maintained,
    ;;; speaks Discord's own gateway, and behaves inside vterm.
    ;;;
    ;;; Every third-party Discord client logs in as a user account, which
    ;;; Discord's terms forbid -- discordo's README says so in its first line,
    ;;; and accounts do get banned for it. Use one you can afford to lose.
    ;;;
    ;;; First run shows discordo's login screen: pick "Login with QR" and scan
    ;;; it with the Discord phone app. The token goes to the macOS Keychain,
    ;;; not to a file.
    ;;;
    ;;; Named *discord*, not *term:discord*: that prefix is the bottom-panel
    ;;; rule in plugins/keybinds, ten lines tall. <escape> goes to discordo,
    ;;; which uses it to close panes and dialogs; C-\ is the way out to normal
    ;;; state, as in the claude-code terminals (keybinds.nix).
    ;;;
    ;;; The defvar is load-bearing. vterm is not loaded when this file is
    ;;; byte-compiled, so without it the `let' below binds vterm-shell
    ;;; lexically, vterm never sees it, and SPC o i opens a plain zsh.
    (defvar vterm-shell)

    (defun my/discord ()
      "Show Discord, starting discordo in its own terminal if it is not running."
      (interactive)
      (let ((buffer (get-buffer "*discord*")))
        (unless (and buffer (get-buffer-process buffer))
          (when buffer
            (kill-buffer buffer))
          (let ((vterm-shell "${lib.getExe pkgs.discordo}"))
            (setq buffer (save-window-excursion (vterm "*discord*"))))
          (with-current-buffer buffer
            (setq-local my/vterm-escape-target 'process)
            ;; On this one process's filter, not on `vterm--filter': the other
            ;; terminals never pay for the scan.
            (add-function :before (process-filter (get-buffer-process buffer))
                          #'my/discord--scan)))
        (switch-to-buffer buffer)
        (when (fboundp 'evil-insert-state)
          (evil-insert-state))))

    (defun my/discord-running-p ()
      "Non-nil while discordo is running in *discord*."
      (let ((buffer (get-buffer "*discord*")))
        (and buffer (process-live-p (get-buffer-process buffer)))))

    ;;; Discord pings: the banner, and the count in the tab bar.
    ;;;
    ;;; discordo posts notifications the terminal way. tcell writes OSC 777 --
    ;;; ESC ] 777 ; notify ; TITLE ; BODY ESC \ -- into its output and leaves
    ;;; the rest to the terminal. vterm has no handler for 777: libvterm parses
    ;;; the sequence and drops it, so inside Emacs every ping vanished without
    ;;; a trace.
    ;;;
    ;;; The sequence is picked out of discordo's output on its way into vterm,
    ;;; which still receives every byte. Each one becomes a banner through
    ;;; `my/notify' -- the same door telega and Slack go through -- and bumps
    ;;; `my/discord-pings', which the tab bar shows (statusline.nix).
    ;;;
    ;;; discordo only notifies for messages that mention you, so that is what
    ;;; this counts: pings since you last looked, not Discord's unread total,
    ;;; which discordo keeps to itself. Looking at *discord* resets it.
    (defvar my/discord-pings 0
      "Discord mentions since the *discord* buffer was last on screen.")

    (defvar-local my/discord--tail ""
      "An OSC 777 sequence cut off by the end of the last chunk of output.")

    (defun my/discord--showing-p ()
      "Non-nil when *discord* is the buffer in the selected window."
      (eq (window-buffer (selected-window)) (get-buffer "*discord*")))

    (defun my/discord--ping (title body)
      "Count a Discord mention and post it, unless it is already on screen."
      (unless (my/discord--showing-p)
        (setq my/discord-pings (1+ my/discord-pings))
        (my/notify (if (string-empty-p title) "Discord" title) body)
        (force-mode-line-update t)))

    ;; vterm reads its process as `binary', so INPUT is raw bytes: a name or a
    ;; message with accents arrives as UTF-8 and is decoded here.
    (defun my/discord--scan (proc input)
      "Turn the OSC 777 notifications in PROC's INPUT into pings."
      (when (buffer-live-p (process-buffer proc))
        (with-current-buffer (process-buffer proc)
          (let ((text (concat my/discord--tail input))
                (start 0))
            (setq my/discord--tail "")
            (while (string-match
                    "\e]777;notify;\\([^;\a\e]*\\);\\([^\a\e]*\\)\\(?:\a\\|\e\\\\\\)"
                    text start)
              (my/discord--ping (decode-coding-string (match-string 1 text) 'utf-8)
                                (decode-coding-string (match-string 2 text) 'utf-8))
              (setq start (match-end 0)))
            ;; An opener whose terminator has not arrived yet waits for the
            ;; next chunk. Capped, so a sequence that never closes cannot grow
            ;; without bound.
            (when (and (string-match "\e]777;[^\a\e]*\\'" text start)
                       (< (- (length text) (match-beginning 0)) 4096))
              (setq my/discord--tail (substring text (match-beginning 0))))))))

    (defun my/discord--seen (&rest _)
      "Clear the ping count once *discord* is on screen."
      (when (and (> my/discord-pings 0) (my/discord--showing-p))
        (setq my/discord-pings 0)
        (force-mode-line-update t)))

    (add-hook 'window-selection-change-functions #'my/discord--seen)
    (add-hook 'window-buffer-change-functions #'my/discord--seen)
  '';
}
